$env:NODE_ID="node1"
$env:REST_PORT="8081"
$env:GRPC_PORT="50051"
$env:DATA_DIRECTORY="d:\RAFT\data\node1"
$env:PEER_NODES="node1:localhost:50051,node2:localhost:50052,node3:localhost:50053"
$env:LOG_LEVEL="INFO"
Start-Process java -ArgumentList "-jar d:\RAFT\atlaskv-server\target\atlaskv-server-0.1.0-SNAPSHOT-exec.jar" -NoNewWindow -RedirectStandardOutput "d:\RAFT\data\node1.log" -RedirectStandardError "d:\RAFT\data\node1.err"

$env:NODE_ID="node2"
$env:REST_PORT="8082"
$env:GRPC_PORT="50052"
$env:DATA_DIRECTORY="d:\RAFT\data\node2"
$env:PEER_NODES="node1:localhost:50051,node2:localhost:50052,node3:localhost:50053"
$env:LOG_LEVEL="INFO"
Start-Process java -ArgumentList "-jar d:\RAFT\atlaskv-server\target\atlaskv-server-0.1.0-SNAPSHOT-exec.jar" -NoNewWindow -RedirectStandardOutput "d:\RAFT\data\node2.log" -RedirectStandardError "d:\RAFT\data\node2.err"

$env:NODE_ID="node3"
$env:REST_PORT="8083"
$env:GRPC_PORT="50053"
$env:DATA_DIRECTORY="d:\RAFT\data\node3"
$env:PEER_NODES="node1:localhost:50051,node2:localhost:50052,node3:localhost:50053"
$env:LOG_LEVEL="INFO"
Start-Process java -ArgumentList "-jar d:\RAFT\atlaskv-server\target\atlaskv-server-0.1.0-SNAPSHOT-exec.jar" -NoNewWindow -RedirectStandardOutput "d:\RAFT\data\node3.log" -RedirectStandardError "d:\RAFT\data\node3.err"
